### PR TITLE
Retry requests automatically on ConflictError

### PR DESCRIPTION
**Pull request by masipcat**
Related https://github.com/guillotinaweb/guillotina_elasticsearch/issues/45#issuecomment-446058917

Any idea on how to test this?

### CODE REVIEW

**Comment by masipcat** [comment]
While implementing the retry logic I found the following cases:

1. `ConflictIdOnContainer` doesn't inherit from `ConflictError`: https://github.com/plone/guillotina/blob/8845454a784e797b90951580e1ab5fa9172055e1/guillotina/exceptions.py#L46 is this correct?
2. It seems that Dummy database implementation doesn't use `ob._p_serial` and doesn't fail if mismatch with the expected value. I think that dummy db should fail as well.

Finally, do you know what I'm missing to make tests using postgres work on travis?

Thank you!

**Comment by vangheem** [comment]
1) Yes, this is correct. ConflictIdOnContainer is when there is an object with the same id in the container as you are trying to add. It is like the http conflict status code. It's API related, not db related.
2) Yes, that is fine. We never really spent much time on the dummy db so I'm sure it's missing a lot!

Take a look here for pg: https://github.com/plone/guillotina/blob/master/.travis.yml

There are some nuances with db setup you'll need to add.

**Comment by masipcat** [comment]
@vangheem It seem's that guillotina doens't link `jsonschema` 3.x

**Comment by vangheem** [comment]
@masipcat ahh, thanks for the heads up. I made an issue for it: https://github.com/plone/guillotina/issues/439

Is this PR ready for merge/release?

**Comment by masipcat** [comment]
@vangheem yes, ready!

**Pull request merged**
