### PR TITLE
Added GET param `eager-commit`

### PR DESCRIPTION
**Pull request by masipcat**
At the end I found how to implement this in a easy way and I realized doesn't make sense to create a service

### CODE REVIEW

**Comment by masipcat** [comment]
Btw, `test_querying_permissions` is failing in my branch but also in master and I don't know how to fix it.

**Comment by vangheem** [comment]
huh, 404, would you be able to see why it is getting a 404 there?

**Comment by masipcat** [comment]
@vangheem the problem is here: https://github.com/guillotinaweb/guillotina_batch/pull/10/files#diff-73c155ff484360f170707d364d2cf31dR168 

The value of `tail` must be `@canido` instead of `@canido?permission=guillotina.ChangePermissions`

**Comment by masipcat** [comment]
(If you approve the PR, please squash commits on merge)

**Comment by masipcat** [comment]
you're welcome :)

**Pull request merged**
