### PR TITLE
Move to g6 + support py3.8

### PR DESCRIPTION
**Pull request by lferran**

### CODE REVIEW

**Comment by lferran** [comment]
@masipcat could help me out here? Tests fail when running with `DATABASE=postgresql` with the following traceback:

```
packages/guillotina/db/storages/pg.py", line 933, in get_one_row
    conn = await txn.get_connection()
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/guillotina/db/transaction.py", line 156, in get_connection
    self._db_conn = await self._manager._storage.open()
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/guillotina/db/storages/pg.py", line 300, in decorator
    return await f(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/guillotina/db/storages/pg.py", line 797, in open
    return await self.pool.acquire(timeout=self._conn_acquire_timeout)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/asyncpg/pool.py", line 475, in _acquire
    return await asyncio.wait_for(
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/asyncio/tasks.py", line 476, in wait_for
    await waiter
RuntimeError: Task <Task pending name='Task-35' coro=<double_to_single_callable.<locals>.new_application() running at /opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/async_asgi_testclient/compatibility.py:63> cb=[_callback(<bound method... _getters[1]>>)() at /opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/async_asgi_testclient/utils.py:92]> got Future <Future pending> attached to a different loop
```

when entering in the `container_requester` fixture context manager. Am I missing something?

any ideas?

**Comment by masipcat** [comment]
In g6 you need to add `pytest.mark.asyncio` decortor in each test or at module level (https://github.com/plone/guillotina/blob/208089cfd19dff3cfc8e1c23ea21dd2a2bca493d/guillotina/tests/redis/test_driver.py#L7)

Also, you shouldn't use the fixture `loop` (from aiohttp fixtures) because creates a different loop. In g6 we use the fixture `event_loop` . I think you don't need aiohttp anymore and you can remove this: https://github.com/guillotinaweb/guillotina_batch/blob/master/guillotina_batch/tests/conftest.py#L2


I hope this solves the problem!

**Comment by lferran** [comment]
thanks @masipcat ! adding `pytestmark = pytest.mark.asyncio` solved it

**Review by vangheem — APPROVED** [review]

**Comment by vangheem** [comment]
6.0.0 released

**Pull request merged**
